# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c711686d22e3173bc43917d5c8af8f0cdb59f74b3f16e67b52770c4c8399bba615daf9d6cae2683839511390bf6eeee2d474904b0ae11ff49da847e5b7484295

test:
  secret_key_base: 2eecb136e247671dbe3cced707666c1fe5ff7c46c7d1785010223e202bb9108531a1c1bf0d0476d821c3385a2810b9393a9e336575dff425013bb351792f2daf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>